<section id="important_dates">
	<h2>Important Dates</h2>
	
	<article>
		<h3>April 25, 2012</h3>
		<p>Open Mic at the Buzz<br/>
			6:30-8:30 p.m.</p>
	</article>
	<article>
		<h3>April 25 & 26, 2012</h3>
		<p>Information Table in EMU<br/>
			9 a.m.-5 p.m.</p>
	</article>
		<article>
		<h3>April 26, 2012</h3>
		<p>Reading: Andrew Hudgins<br/>
			8 p.m., Knight Library <br/>Browsing Room</p>
	</article>
	<article>
		<h3>May 3, 2012</h3>
		<p>Unbound Benefit Show<br/>
			Luckey's, 9 p.m.</p>
	</article>
	<article>								
		<h3>May 10, 2012</h3>
		<p>Reading: Randall Kenan<br/>
			8 p.m., Gerlinger Alumni Lounge</p>
	</article>
	<article>
		<h3>May 10, 2012</h3>
		<p>Bake Sale: UO Duck Store<br/>
			9 a.m.-5 p.m.</p>
	</article>
	<article>
		<h3>May 16, 2012</h3>
		<p>Open Mic at the Buzz<br/>
		6:30-8:30 p.m.</p>
	</article>
	<article>
		<h3>June 5, 2012</h3>
		<p>Submission Deadline<br/>
		for our Spring 2012 issue</p>
	</article>
</section>