<section id="events">
	<h2>Readings &amp; Events</h2>
	<div class="scrollable">
		<article>
			<h3>Live Lit West: Carl Swart &amp; Jacob Berns</h3>
			<p>Friday, April 13th, 2012<br/>
			Tsunami Books, 7 p.m.</p>
		</article>
		<article>
			<h3>Unbound Hosts First Open Mic of Spring Term</h3>
			<p>Wednesday, April 25th, 2012<br/>
			The Buzz, 6:30-8:30 p.m.</p>
		</article>
		<article>
			<h3>Author Andrew Hudgins Reading at UO</h3>
			<p>Thursday, April 26th, 2012<br/>
			Knight Library Browsing Room, 8 p.m.</p>
		</article>
		<article>
			<h3>Unbound Information Table</h3>
			<p>Wednesday & Thursday, April 25th and 26th<br/>
			2012 EMU Main Lobby, 8 a.m. - 5 p.m.</p>
		</article>
		<article>
			<h3>Unbound Benefit Show</h3>
			<p>Featuring Beard of Spiders, Soccer Babes, & The Great Hiatum<br/>
			Thurday, May 3rd, 2012 @ 9 p.m.<br/>
			Luckey's Bar, $5 Cover</p>
		</article>
		<article>
			<h3>Author Randall Kenan Reading at UO</h3>
			<p>Thursday, May 10th, 2012<br/>
			Gerlinger Hall Alumni Lounge, 8 p.m. (EMU)</p>
		</article>
		<article>
			<h3>Unbound Bake Sale</h3>
			<p>Thursday, May 10th, 2012<br/>
			UO Duck Store, 9 a.m.-5 p.m.</p>
		</article>
		<article>
			<h3>Live Lit West: Nick Malick & MFA First Years</h3>
			<p>Friday, May 14th, 2012<br/>
				Tsunami Books, 6:30-8:30 p.m.</p>
		</article>
		<article>
			<h3>Unbound Hosted Open Mic</h3>
			<p>Wednesday, May 16th, 2012<br/>
			The Buzz, 6:30-8:30 p.m.</p>
		</article>			
	</div>
</section>
