<section id="spotlight">
	<!--<h2><span class="gray">((</span> <span class="header_color">Spotlight Section</span> <span class="gray">))</span></h2>-->
	<h2>Spotlight</h2>
	<img src="images/noellepicture.jpg" class="black_border" style="float:right; width:200px; margin: 0 0 15px 15px" />
	<br/>
	<p>The Spotlight section is a new addition to the Unbound website where we highlight one student artist in the areas of art, fiction, and poetry each term. For Spring term we've selected a poet, Noelle Petrowski, who has been published in all three of Unbound's 2011 issues. You can read more about Noelle and her poetry below!</p>
	<br/>
	<p class="italic right">Interview and article<br/> by Bryan Atkinson</p>
	<br/>
	<p>
	Noelle Petrowski's poem "Where Snow Comes From" (Unbound, Fall 2011) was perfectly fitting for the barrage of snow we received this year. As the Dogwood trees bloomed and the birds warmed up their vocal chords, the snow created a beautiful white backdrop for flowers but stifled the birds. It is those bittersweet qualities of nature that Noelle is drawn to.
	</p>

	<p>
	"I think the bittersweet is where I'm finding myself going over and over again," she says. "I'm really inspired by nature, but I also think that humans screw it up a lot. I think that's often something I play with."
	</p>
	
	<p class="right"><a href="spotlight.php">Read More</a></p>
</section>