<header>
	<div id="social">	
		<a href="http://facebook.com/unboundmagazine" target="new"><img id="facebook" src="images/facebook.png" alt="visit us on Facebook page" /></a>
		<a href="http://twitter.com/unboundmagazine" target="new"><img id="twitter" src="images/twitter.png" alt="follow us on Twitter" /></a>
		<a href="http://www.linkedin.com/pub/unbound-magazine/39/473/29" target="new"><img id="linkedin" src="images/linkedin.gif" alt="visit us on Linkedin"></a>
	</div>
	
	<a href="/"><h1>Unbound</h1></a>
	<p>Art Fiction Poetry</p>
</header>