<section id="mailing_list">
	<h2>Mailing List</h2>
	<form action="javascript:submit_mailing_list();">
	<p>Sign up for Unbound's monthly mailing list to receive information about literary art happenings around the UO campus, including the Visiting Writer's Series, Live Lit West, Unbound fundraisers, open mics, and other fun events!</p>
	<br />
		<table>
			<tr>
				<td style="text-align:right">Name:&nbsp;</td> <td><input type="text" name="name" value=""></td>
			</tr>
		
			<tr>
				<td style="text-align:right">E-mail:&nbsp;</td>
				<td><input type="text" name="email" value=""></td>
			</tr>
		</table>
		<br/>
		<p style="text-align:center"><input type="submit" value="Sign up" /></p>
	</form>
</section>