<nav>
	<ul>
		<li><a href="index.php">Home</a></li>
		<li><a href="archive.php">Archive</a></li>
		<li><a href="issue.php?iss=Current Issue">Current Issue</a></li>
		<li><a href="submission_guidelines.php">Submission Guidelines</a></li>
		<li><a href="editing_staff.php">Staff</a></li>
		<li><a href="/index.php#about">About</a></li>
		<li><a href="apply.php">Apply</a></li>
		<li><a href="links.php">Links</a></li>
	</ul>
</nav>