<section id="news">
	<h2>News</h2>
	<div class="scrollable">
		<article>
			<h3>Unbound Winter 2012 Issue Out!</h3>
			<p>Our latest issue, Winter 2012: Volume 5, Issue 2, is now out!<br/>
			Check it out <a href="">here</a>!</p>
		</article>
		<article>
			<h3>Kidd Competition Deadline: April 16th</h3>
			<p>Submit your fiction and poetry to the Kidd Writing Competition
by 12 p.m., Monday, April 16th! The 2012 judges are Andrew Hudgins in poetry
and Randall Kenan in fiction. More information can be found <a href="">here</a></p>
		</article>
		<article>
			<h3>Find Unbound on Twitter</h3>
			<p>Unbound has given in and joined the world of Twitter! Follow us here. (link)</p>
		</article>
		<article>
			<h3>Unbound Fall 2011 Issue Now Out</h3>
			<p>Unbound's Fall 2011 issue is now up for viewing! Huge thanks to all who submitted!</p>
		</article>
		<article>
			<h3>Congratulations to the Winners of Our<br/>
			Fall 2011 Contest!</h3>
			<p>You can find their work in the beginning of<br/>
			Unbound's Fall issue!<br />
			ART: "Roses in Her Eyes" by Anna Chelsky<br />
			FICTION: "Gradients" by Amanda Berg<br />
			POETRY: "Cigarettes and Rain" by Maggie Brees</p>
		</article>
		<article>
			<h3>Unbound is Having an Art, Fiction, <br/>
			and Poetry Contest!</h3>
			<p>Take one line from your favorite song, or another of your choosing, and use it as a prompt for a short story, poem, or as inspiration for a piece of art! Send all submissions and questions to unboundlit@gmail.com. Please include song title and name with entry.</p>
			<p>Deadline: Monday, November 28th, 2011</p>
		</article>
		<article>
			<h3>Find Unbound on Facebook!</h3>
			<p>Did you know Unbound has an active Facebook page? Click the Facebook icon box to get connected now! Like our page and you'll see weekly updates on readings, events, literary releases, and more!</p>
		</article>
		<article>
			<h3>UO Creative Writing Program Ranked<br/>8th in Nation!</h3>
			<p>University of Oregon's MFA Creative Writing program is now ranked 8th in the country!</p>
		</article>
		<article>
			<h3>Congratulations to the Winners of our 2010 Horror-Genre Contest!</h3>
			<p>You can find their work in the front of Unbound's Fall issue!<br />
			ART: "Hearts for Breakfast" by Maggie Brees<br/>
			FICTION: "Black Dress" by Megan Gibbs<br/>
			POETRY: "Untitled" by Stu White</p>
		</article>
		<article>
			<h3>UO Welcomes Danny Anderson to Staff</h3>
			<p>Help us welcome professor and poet Danny Anderson to the UO Creative Writing staff!</p>
		</article>
		<article>
			<h3>Creative Writing Minor Approved!</h3>
			<p>The Creative Writing minor for undergraduates at UO has been approved! You can find information about this and the Kidd Tutorials here. (link)</p>
		</article>
	</div>
</section>