<section id="past_issues">
	<a href="issue.php?iss=Current Issue"><img src="images/issues/current_issue.jpg" /></a>
	<a href="issue.php?iss=Volume 5, Issue 1"><img src="images/issues/vol_5_iss_1.jpg" /></a>
	<a href="issue.php?iss=Volume 4, Issue 3"><img src="images/issues/vol_4_iss_3.png" /></a>
	<a href="issue.php?iss=Volume 4, Issue 2"><img src="images/issues/vol_4_iss_2.png" /></a>
	<a href="issue.php?iss=Volume 4, Issue 1"><img src="images/issues/vol_4_iss_1.jpg" /></a>
</section>